// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfSwgK9ObHUpmzltIK1jIYS8bpAtc-tZg',
    appId: '1:1038670080495:web:fd06171491e0b151092e1a',
    messagingSenderId: '1038670080495',
    projectId: 'expense-track-app-fe258',
    authDomain: 'expense-track-app-fe258.firebaseapp.com',
    storageBucket: 'expense-track-app-fe258.firebasestorage.app',
    measurementId: 'G-QJENE4724C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCrbCHf6nMAoQwr3sLmr5zXvA1X96U7UY',
    appId: '1:1038670080495:android:b7f017ad240ecbbc092e1a',
    messagingSenderId: '1038670080495',
    projectId: 'expense-track-app-fe258',
    storageBucket: 'expense-track-app-fe258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrce64QR2QPNmYXGVI8kuPCxPJqmXIE4w',
    appId: '1:1038670080495:ios:7640f87077d11452092e1a',
    messagingSenderId: '1038670080495',
    projectId: 'expense-track-app-fe258',
    storageBucket: 'expense-track-app-fe258.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrce64QR2QPNmYXGVI8kuPCxPJqmXIE4w',
    appId: '1:1038670080495:ios:7640f87077d11452092e1a',
    messagingSenderId: '1038670080495',
    projectId: 'expense-track-app-fe258',
    storageBucket: 'expense-track-app-fe258.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfSwgK9ObHUpmzltIK1jIYS8bpAtc-tZg',
    appId: '1:1038670080495:web:110c729f52746af5092e1a',
    messagingSenderId: '1038670080495',
    projectId: 'expense-track-app-fe258',
    authDomain: 'expense-track-app-fe258.firebaseapp.com',
    storageBucket: 'expense-track-app-fe258.firebasestorage.app',
    measurementId: 'G-V3WKJ40R8K',
  );
}
